// Generated by scripts/generate-types.mjs. Do not edit.
// Canonical source: JSON Schema 2020-12, OpenRails Shared Interface 1.0.1.

export type Actor = {
  authorityStatus: "UNVERIFIED" | "VERIFIED" | "SUSPENDED" | "REVOKED";
  createdAt: Timestamp;
  displayName: string;
  extensions?: ExtensionData;
  externalSubject?: Identifier;
  id: Identifier;
  interfaceVersion: InterfaceVersion;
  kind: "person" | "application" | "agent" | "service" | "sidecar";
  provenance: Provenance;
  walletAddress?: NonZeroAddress;
};
export type ActorListResponse = {
  actors: Array<Actor>;
};
export type ActorRef = ObjectRef & {
  type?: "Actor";
};
export type ActorRequest = {
  actor: Actor;
};
export type ActorResponse = {
  actor: Actor;
};
export type Address = string;
export type Asset = {
  address: Address;
  decimals: number;
  kind: "erc20" | "native";
  symbol: string;
};
export type AuthorizationClass = "PUBLIC_READ" | "AUTHENTICATED_READ" | "PREPARE_ONLY" | "WALLET_SIGNATURE" | "WALLET_TRANSACTION" | "RELAY_SIGNED_ENVELOPE" | "OPERATOR_ADMIN";
export type BaphometDecision = {
  decidedAt: Timestamp;
  decision: "ALLOW" | "BLOCK";
  effects: {
    financialEffect: "NONE" | "PENDING" | "CONFIRMED";
    paycardCreated: boolean;
    valueMoved: boolean;
    walletAction: "NONE" | "REQUIRED" | "SUBMITTED";
  };
  executionProfile: "delegated-runtime";
  extensions?: ExtensionData;
  id: Identifier;
  inputHash: Hash;
  interfaceVersion: InterfaceVersion;
  pactRef?: PactRef;
  policyVersion: Identifier;
  proposalRef: ProposalRef;
  provenance: Provenance;
  reasonCodes: Array<Identifier>;
};
export type BaphometDecisionRef = ObjectRef & {
  type?: "BaphometDecision";
};
export type CanonicalReconciliation = {
  actualAmount?: NonNegativeIntegerString;
  expectedAmount?: NonNegativeIntegerString;
  observedAt: Timestamp;
  reason?: string;
  stateHash?: Hash;
  status: "MATCHED" | "MISMATCHED" | "PENDING" | "NOT_APPLICABLE";
  vaultRef?: PaycardStreamRef;
};
export type CapabilitiesResponse = {
  capabilities: Array<CapabilityDeclaration>;
};
export type CapabilityDeclaration = {
  allowedExecutionProfiles: Array<ExecutionProfile>;
  authorizationClasses: Array<AuthorizationClass>;
  capability: string;
  evidence: Array<Identifier>;
  interfaceVersion: InterfaceVersion;
  provenance: Provenance;
  status: CapabilityStatus;
  statusJustification: string;
  transactionBehavior: {
    financialSuccessRequirement: "none" | "exact-receipt-and-vault-reconciliation";
    kind: "read-only" | "runtime-evaluation" | "wallet-signature" | "wallet-transaction" | "relay-signed-envelope";
    submissionMeansFinancialSuccess: false;
  };
};
export type CapabilityDeclarationRef = ObjectRef & {
  type?: "CapabilityDeclaration";
};
export type CapabilityList = {
  capabilities: Array<string>;
  interfaceVersion: InterfaceVersion;
};
export type CapabilityStatus = "VERIFIED" | "LIVE" | "RECORDED" | "DEMONSTRATION" | "PLANNED" | "UNAVAILABLE";
export type ChainId = string;
export type DecisionResponse = {
  decision: BaphometDecision;
};
export type EmptyRequest = {
};
export type ErrorCode = "INPUT_INVALID" | "NETWORK_UNSUPPORTED" | "CAPABILITY_UNAVAILABLE" | "WRONG_NETWORK" | "AUTHORIZATION_REQUIRED" | "WALLET_REJECTED" | "SIGNATURE_INVALID" | "SIGNATURE_EXPIRED" | "NONCE_CONFLICT" | "POLICY_BLOCKED" | "TERMS_MISMATCH" | "PROOF_REQUIRED" | "PROOF_INVALID" | "INSUFFICIENT_BALANCE" | "INSUFFICIENT_ALLOWANCE" | "RPC_UNAVAILABLE" | "SIMULATION_REVERTED" | "TRANSACTION_REVERTED" | "TRANSACTION_REPLACED" | "TRANSACTION_DROPPED" | "RECEIPT_UNVERIFIED" | "STATE_STALE" | "RATE_LIMITED" | "INTERNAL_ERROR";
export type ExactVerification = {
  contractAddress: NonZeroAddress;
  eventIndex: NonNegativeIntegerString;
  eventName: string;
  eventSignature: string;
  observedValuesHash: Hash;
};
export type ExecutionProfile = "direct-wallet-authorized" | "delegated-runtime";
export type ExtensionData = {
  [key: `x-${string}`]: unknown;
};
export type GaiaCase = {
  caseType: "DISPUTE" | "RECTIFICATION" | "EXCEPTION" | "RECONCILIATION";
  executionProfile: "delegated-runtime";
  extensions?: ExtensionData;
  id: Identifier;
  interfaceVersion: InterfaceVersion;
  obligationRefs?: Array<RectificationObligationRef>;
  openedAt: Timestamp;
  pathRef?: PathRef;
  provenance: Provenance;
  resolvedAt?: Timestamp;
  status: "OPEN" | "RESOLVING" | "RESOLVED" | "CLOSED";
  subjectRef: SubjectObjectRef;
  workspaceRef: WorkspaceRef;
};
export type GaiaCaseRef = ObjectRef & {
  type?: "GaiaCase";
};
export type GaiaCaseRefRequest = {
  objectRef: GaiaCaseRef;
};
export type GaiaCaseRequest = {
  case: GaiaCase;
};
export type GaiaCaseResponse = {
  case: GaiaCase;
};
export type GaiaResolveRequest = {
  caseRef: GaiaCaseRef;
  obligationRefs: Array<RectificationObligationRef>;
};
export type Hash = string;
export type HexData = string;
export type Identifier = string;
export type Intent = {
  action: "CREATE_RAILSFLOW" | "PAY_RAILSFLOW" | "ISSUE_RAILSCARD" | "CLAIM_RAILSCARD" | "OPEN_PAYCARD" | "SETTLE_PAYCARD" | "FLUSH_RESIDUAL";
  createdAt: Timestamp;
  executionProfile: ExecutionProfile;
  expiresAt: Timestamp;
  extensions?: ExtensionData;
  id: Identifier;
  interfaceVersion: InterfaceVersion;
  nonce: NonNegativeIntegerString;
  pactRef?: PactRef;
  pathRef?: PathRef;
  paymentTerms: PaymentTerms;
  provenance: Provenance;
  requestedNetwork?: NetworkReference;
  status: LifecycleState;
  subject: Subject;
  workspaceRef?: WorkspaceRef;
};
export type IntentRef = ObjectRef & {
  type?: "Intent";
};
export type IntentRequest = {
  intent: Intent;
};
export type IntentResponse = {
  intent: Intent;
};
export type InterfaceError = {
  actualNetwork?: NetworkReference;
  code: ErrorCode;
  details?: {
    field?: string;
    providerCode?: string;
    reason?: string;
  };
  expectedNetwork?: NetworkReference;
  expiresAt?: Timestamp;
  financialEffect: "NONE" | "PENDING" | "UNKNOWN" | "RECONCILIATION_REQUIRED";
  interfaceVersion: InterfaceVersion;
  lifecycleState: LifecycleState;
  message: string;
  occurredAt: Timestamp;
  operationId: Identifier;
  provenance: Provenance;
  retryable: boolean;
  transactionState: TransactionStateName;
};
export type InterfaceErrorRef = ObjectRef & {
  type?: "InterfaceError";
};
export type InterfaceVersion = "1.0.1";
export type LifecycleState = "DRAFT" | "PREPARED" | "AWAITING_AUTHORIZATION" | "EVALUATING" | "BLOCKED" | "ALLOWED" | "COMMITTED" | "EXECUTING" | "PROOF_PENDING" | "PROOF_VERIFIED" | "CLEARING_READY" | "SUBMITTED" | "CONFIRMED" | "SETTLING" | "SETTLED" | "RESOLVING" | "RESOLVED" | "FAILED" | "CANCELLED";
export type ManifestIndex = {
  interfaceVersion: InterfaceVersion;
  manifests: Array<string>;
};
export type NetworkIdRequest = {
  networkId: Identifier;
};
export type NetworkListResponse = {
  networks: Array<NetworkManifest>;
};
export type NetworkManifest = {
  capabilities: Array<CapabilityDeclaration>;
  chainId: ChainId;
  contracts: Array<{
    address: NonZeroAddress;
    id: Identifier;
    provenance: Provenance;
    role: "settlement" | "asset" | "gateway-wallet" | "gateway-minter" | "vault" | "other";
    status: CapabilityStatus;
  }>;
  displayName: string;
  explorer: {
    addressUrlTemplate: string;
    baseUrl: string;
    transactionUrlTemplate: string;
  };
  finalityPolicy: {
    confirmationModel: "receipt-and-vault-reconciliation" | "receipt-only" | "runtime-record";
    financialSuccessRequires: Array<"CONFIRMED_TRANSACTION" | "EXACT_EVENT_VERIFICATION" | "CANONICAL_VAULT_RECONCILIATION">;
    reorgHandling: string;
    requiredConfirmations: NonNegativeIntegerString;
  };
  interfaceVersion: InterfaceVersion;
  nativeAsset: Asset;
  networkId: Identifier;
  provenance: Provenance;
  receiptMappings: Array<{
    contextRequirements?: Array<"operationId" | "signatureBinding" | "recipient" | "observedValues">;
    contractId: Identifier;
    eventName: string;
    receiptType: "AUTHORIZATION" | "CLAIM" | "CLEARING" | "SETTLEMENT" | "RESIDUAL" | "RECONCILIATION";
    verificationFields: Array<string>;
  }>;
  rpc: {
    credentialPolicy: "credentials-resolved-outside-package";
    defaultEndpoint: string;
    environmentReferences: Array<string>;
    publicEndpoints: Array<string>;
  };
  runtime: {
    delegatedRuntimeFinancialAuthority: "wallet-boundary";
    workspaceRuntimeStatus: "LIVE" | "NOT_LIVE" | "UNAVAILABLE";
  };
  settlementAssets: Array<Asset>;
  status: CapabilityStatus;
  typedDataDomains: Array<SignatureDomain>;
};
export type NetworkManifestRef = ObjectRef & {
  type?: "NetworkManifest";
};
export type NetworkReference = {
  chainId: ChainId;
  networkId: Identifier;
};
export type NetworkResponse = {
  network: NetworkManifest;
};
export type NonNegativeIntegerString = string;
export type NonZeroAddress = string;
export type ObjectRef = {
  id: Identifier;
  network?: NetworkReference;
  type: ObjectType;
};
export type ObjectType = "Workspace" | "WorkspaceMember" | "Actor" | "Path" | "Intent" | "Proposal" | "BaphometDecision" | "SettlementIntent" | "Pact" | "PaymentTerms" | "WorkUsageEvent" | "ProofPolicy" | "Proof" | "RailsFlow" | "RailsCard" | "PaycardStream" | "Receipt" | "GaiaCase" | "RectificationObligation" | "InterfaceError" | "TransactionState" | "OperationEnvelope" | "NetworkManifest" | "CapabilityDeclaration" | "Provenance";
export type OperationEnvelope = {
  authorizationClass: AuthorizationClass;
  capability: string;
  createdAt: Timestamp;
  data: Workspace | WorkspaceMember | Actor | Path | Intent | Proposal | BaphometDecision | SettlementIntent | Pact | WorkUsageEvent | Proof | RailsFlow | RailsCard | PaycardStream | Receipt | GaiaCase | RectificationObligation | NetworkManifest | CapabilityDeclaration;
  errors: Array<InterfaceError>;
  executionProfile: ExecutionProfile;
  intentRef?: IntentRef;
  interfaceVersion: InterfaceVersion;
  lifecycleState: LifecycleState;
  network: NetworkReference;
  operationId: Identifier;
  pactRef?: PactRef;
  pathRef?: PathRef;
  proofRefs?: Array<ProofRef>;
  proposalRef?: ProposalRef;
  provenance: Provenance;
  receipts?: Array<Receipt>;
  subject: Subject;
  transaction?: TransactionState;
  updatedAt?: Timestamp;
  workspaceRef?: WorkspaceRef;
};
export type OperationEnvelopeRef = ObjectRef & {
  type?: "OperationEnvelope";
};
export type OperationRegistry = {
  interfaceVersion: InterfaceVersion;
  operations: Array<{
    allowedExecutionProfiles: Array<ExecutionProfile>;
    authorizationClass: AuthorizationClass;
    capability: string;
    capabilityStatusBehavior: {
      onDemonstration: "prepare-or-explain-only; do not claim live financial success";
      onRecorded: "preserve provenance and do not upgrade to LIVE without new evidence";
      onUnavailable: {
        errorCode: "CAPABILITY_UNAVAILABLE";
        financialEffect: "NONE";
        lifecycleState: "FAILED";
        retryable: boolean;
        transactionState: "NOT_REQUESTED";
      };
      successClaimRule: "financial success requires exact verified receipt and canonical reconciliation";
    };
    operationId: string;
    requestDataSchema: string;
    requestSchema: string;
    responseDataSchema: string;
    responseSchema: string;
    transactionBehavior: {
      failureCodes: Array<ErrorCode>;
      financialSuccessRequirement: "none" | "exact-receipt-and-vault-reconciliation";
      kind: "read-only" | "runtime-evaluation" | "wallet-signature" | "wallet-transaction" | "relay-signed-envelope";
      submissionMeansFinancialSuccess: false;
    };
  }>;
  registryVersion: string;
  sourceCapabilities: "Product Foundry shared-interface.yaml";
};
export type OperationRequest = {
  authorizationClass: AuthorizationClass;
  capability: string;
  createdAt: Timestamp;
  data: EmptyRequest | NetworkIdRequest | WorkspaceRefRequest | PathRefRequest | PactRefRequest | ProofRefRequest | PaycardRefRequest | ReceiptRefRequest | GaiaCaseRefRequest | WorkspaceRequest | ActorRequest | PathRequest | PathEvaluateRequest | IntentRequest | ProposalRequest | PactRequest | ProofRequest | RailsFlowRequest | RailsFlowInspectRequest | RailsFlowPayRequest | RailsCardRequest | RailsCardInspectRequest | RailsCardClaimRequest | PaycardOpenRequest | PaycardActionRequest | PaycardListRequest | ReceiptListRequest | ReceiptVerifyRequest | GaiaCaseRequest | GaiaResolveRequest;
  executionProfile: ExecutionProfile;
  intentRef?: IntentRef;
  interfaceVersion: InterfaceVersion;
  network: NetworkReference;
  operationId: string;
  pactRef?: PactRef;
  pathRef?: PathRef;
  proofRefs?: Array<ProofRef>;
  proposalRef?: ProposalRef;
  provenance: Provenance;
  subject: Subject;
  workspaceRef?: WorkspaceRef;
};
export type OperationResponse = {
  authorizationClass: AuthorizationClass;
  capability: string;
  createdAt: Timestamp;
  data: null | NetworkListResponse | NetworkResponse | CapabilitiesResponse | WorkspaceResponse | WorkspaceListResponse | ActorResponse | ActorListResponse | PathResponse | DecisionResponse | IntentResponse | ValidationResponse | ProposalResponse | PactResponse | ProofResponse | RailsFlowResponse | RailsCardResponse | PaycardResponse | PaycardListResponse | ReceiptResponse | ReceiptListResponse | GaiaCaseResponse;
  errors: Array<InterfaceError>;
  executionProfile: ExecutionProfile;
  intentRef?: IntentRef;
  interfaceVersion: InterfaceVersion;
  lifecycleState: LifecycleState;
  network: NetworkReference;
  operationId: string;
  pactRef?: PactRef;
  pathRef?: PathRef;
  proofRefs?: Array<ProofRef>;
  proposalRef?: ProposalRef;
  provenance: Provenance;
  receipts?: Array<Receipt>;
  subject: Subject;
  transaction?: TransactionState;
  updatedAt?: Timestamp;
  workspaceRef?: WorkspaceRef;
};
export type Pact = {
  activatedAt?: Timestamp;
  createdAt: Timestamp;
  decisionRef?: BaphometDecisionRef;
  executionProfile: ExecutionProfile;
  extensions?: ExtensionData;
  id: Identifier;
  interfaceVersion: InterfaceVersion;
  parties: Array<ActorRef>;
  pathRef?: PathRef;
  paymentTerms: PaymentTerms;
  proofPolicy: ProofPolicy;
  proposalRef?: ProposalRef;
  provenance: Provenance;
  signatureBinding: SignatureBinding;
  status: "DRAFT" | "ACTIVE" | "REVOKED" | "EXPIRED";
  workspaceRef?: WorkspaceRef;
};
export type PactRef = ObjectRef & {
  type?: "Pact";
};
export type PactRefRequest = {
  objectRef: PactRef;
};
export type PactRequest = {
  pact: Pact;
};
export type PactResponse = {
  pact: Pact;
};
export type Path = {
  capabilities: Array<Identifier>;
  delegateActorRef: ActorRef;
  executionProfile: "delegated-runtime";
  extensions?: ExtensionData;
  id: Identifier;
  interfaceVersion: InterfaceVersion;
  issuerActorRef: ActorRef;
  limits: Array<PathLimit>;
  provenance: Provenance;
  resourceRefs?: Array<PathResourceRef>;
  signatureBinding: SignatureBinding;
  status: "PREPARED" | "ACTIVE" | "REVOKED" | "EXPIRED";
  workspaceRef: WorkspaceRef;
};
export type PathEvaluateRequest = {
  intentRef: IntentRef;
  pathRef: PathRef;
};
export type PathLimit = {
  asset: Asset;
  maxAmount: NonNegativeIntegerString;
  maxAmountPerTransaction?: NonNegativeIntegerString;
  maxLifespanSeconds?: PositiveIntegerString;
  maxTransactionsPerPeriod: PositiveIntegerString;
  maxVelocityPerSecond?: NonNegativeIntegerString;
  periodSeconds: PositiveIntegerString;
};
export type PathRef = ObjectRef & {
  type?: "Path";
};
export type PathRefRequest = {
  objectRef: PathRef;
};
export type PathRequest = {
  path: Path;
};
export type PathResourceRef = ObjectRef & {
  type?: "Workspace" | "Actor" | "Intent" | "Proposal" | "Pact" | "Proof" | "RailsFlow" | "RailsCard" | "PaycardStream" | "Receipt" | "GaiaCase" | "RectificationObligation";
};
export type PathResponse = {
  path: Path;
};
export type PaycardActionRequest = {
  amount?: NonNegativeIntegerString;
  paycardRef: PaycardStreamRef;
  proofRef?: ProofRef;
};
export type PaycardListRequest = {
  network?: NetworkReference;
  walletAddress?: NonZeroAddress;
};
export type PaycardListResponse = {
  paycards: Array<PaycardStream>;
};
export type PaycardOpenRequest = {
  paymentArtifactRef: PaymentArtifactRef;
};
export type PaycardRefRequest = {
  objectRef: PaycardStreamRef;
};
export type PaycardResponse = {
  paycard: PaycardStream;
};
export type PaycardStream = {
  asset: Asset;
  canonicalState: {
    actualFundedAmount?: NonNegativeIntegerString;
    expectedFundedAmount?: NonNegativeIntegerString;
    observedAt: Timestamp;
    status: "MATCHED" | "MISMATCHED" | "PENDING" | "UNKNOWN";
    vaultRecordHash: Hash;
  };
  createdAt: Timestamp;
  executionProfile: ExecutionProfile;
  extensions?: ExtensionData;
  fundedAmount: NonNegativeIntegerString;
  id: Identifier;
  intentRef?: IntentRef;
  interfaceVersion: InterfaceVersion;
  network: NetworkReference;
  pactRef?: PactRef;
  pathRef?: PathRef;
  paycardId: Hash;
  payer: NonZeroAddress;
  proposalRef?: ProposalRef;
  provenance: Provenance;
  recipient: NonZeroAddress;
  settledAmount: NonNegativeIntegerString;
  settlementShape: "one-time" | "streamed";
  status: "PREPARED" | "FUNDED" | "SETTLING" | "SETTLED" | "FLUSHED" | "FAILED" | "CANCELLED";
  transaction: TransactionState;
  vaultAddress: NonZeroAddress;
  workspaceRef?: WorkspaceRef;
};
export type PaycardStreamRef = ObjectRef & {
  type?: "PaycardStream";
};
export type PaymentArtifactRef = RailsFlowRef | RailsCardRef;
export type PaymentTerms = {
  allowanceAmount?: NonNegativeIntegerString;
  amount: PositiveIntegerString;
  asset: Asset;
  lifespanSeconds?: PositiveIntegerString;
  recipient?: NonZeroAddress;
  settlementShape: "one-time" | "streamed";
  velocityPerSecond?: PositiveIntegerString;
};
export type PositiveIntegerString = string;
export type Proof = {
  beforeTransition: "NONE" | "WALLET_SETTLEMENT_INTENT_AUTHORIZATION" | "PAYER_SIGNATURE_AND_ISSUANCE" | "RECIPIENT_CLAIM" | "CHECKPOINT_SETTLEMENT" | "SETTLEMENT";
  evidenceHash: Hash;
  executionProfile: ExecutionProfile;
  extensions?: ExtensionData;
  gate: ProofGate;
  id: Identifier;
  intentRef?: IntentRef;
  interfaceVersion: InterfaceVersion;
  pactRef?: PactRef;
  pathRef?: PathRef;
  placement: "immediately-before";
  policyRef: ProofPolicyRef;
  proposalRef?: ProposalRef;
  provenance: Provenance;
  status: "NOT_REQUIRED" | "SUBMITTED" | "VERIFIED" | "REJECTED";
  subjectRef: SubjectObjectRef;
  submittedAt: Timestamp;
  verifiedAt?: Timestamp;
  verifierActorRef?: ActorRef;
  workspaceRef?: WorkspaceRef;
};
export type ProofGate = "NONE" | "AUTHORIZATION" | "CLAIM" | "CHECKPOINT" | "FINAL_SETTLEMENT";
export type ProofPolicy = {
  beforeTransition: "NONE" | "WALLET_SETTLEMENT_INTENT_AUTHORIZATION" | "PAYER_SIGNATURE_AND_ISSUANCE" | "RECIPIENT_CLAIM" | "CHECKPOINT_SETTLEMENT" | "SETTLEMENT";
  executionProfile: ExecutionProfile;
  extensions?: ExtensionData;
  id: Identifier;
  interfaceVersion: InterfaceVersion;
  placement: "immediately-before";
  policyVersion: Identifier;
  required: boolean;
  requiredGate: ProofGate;
  termsHash: Hash;
};
export type ProofPolicyRef = ObjectRef & {
  type?: "ProofPolicy";
};
export type ProofRef = ObjectRef & {
  type?: "Proof";
};
export type ProofRefRequest = {
  objectRef: ProofRef;
};
export type ProofRequest = {
  proof: Proof;
};
export type ProofResponse = {
  proof: Proof;
};
export type Proposal = {
  createdAt: Timestamp;
  executionProfile: "delegated-runtime";
  extensions?: ExtensionData;
  id: Identifier;
  inputHash: Hash;
  intentRef: IntentRef;
  interfaceVersion: InterfaceVersion;
  normalizedTerms: PaymentTerms;
  pathRef: PathRef;
  policyVersion?: Identifier;
  provenance: Provenance;
  status: "EVALUATING" | "ALLOWED" | "BLOCKED" | "FAILED";
  workspaceRef: WorkspaceRef;
};
export type ProposalRef = ObjectRef & {
  type?: "Proposal";
};
export type ProposalRequest = {
  proposal: Proposal;
};
export type ProposalResponse = {
  proposal: Proposal;
};
export type Provenance = {
  authority: string;
  commit?: string;
  evidenceLevel: "repository-asserted" | "independently-verified" | "buyer-validated" | "configuration-only" | "runtime-observed";
  evidenceRefs?: Array<Identifier>;
  notes?: string;
  observedAt: Timestamp;
  repository?: string;
  source: "repository-evidence" | "network-observation" | "configuration" | "wallet-signed" | "runtime-evaluation" | "operator-record";
};
export type ProvenanceRef = ObjectRef & {
  type?: "Provenance";
};
export type RailsCard = {
  claimPolicy?: "first-claimant" | "recipient-only";
  createdAt: Timestamp;
  executionProfile: ExecutionProfile;
  extensions?: ExtensionData;
  id: Identifier;
  intentRef?: IntentRef;
  interfaceVersion: InterfaceVersion;
  pactRef?: PactRef;
  pathRef?: PathRef;
  paycardRef?: PaycardStreamRef;
  paymentTerms: PaymentTerms;
  proofPolicy: ProofPolicy;
  proposalRef?: ProposalRef;
  provenance: Provenance;
  settlementIntentRef?: SettlementIntentRef;
  signatureBinding: SignatureBinding;
  status: "DRAFT" | "PREPARED" | "AWAITING_AUTHORIZATION" | "COMMITTED" | "EXECUTING" | "SETTLED" | "FAILED" | "CANCELLED" | "EXPIRED";
  variant: "bearer" | "recipient-bound";
  workspaceRef?: WorkspaceRef;
};
export type RailsCardClaimRequest = {
  claimant: NonZeroAddress;
  proofRef?: ProofRef;
  railscardRef: RailsCardRef;
};
export type RailsCardInspectRequest = {
  railscardRef: RailsCardRef;
};
export type RailsCardRef = ObjectRef & {
  type?: "RailsCard";
};
export type RailsCardRequest = {
  railscard: RailsCard;
};
export type RailsCardResponse = {
  railscard: RailsCard;
};
export type RailsFlow = {
  createdAt: Timestamp;
  executionProfile: ExecutionProfile;
  expiresAt: Timestamp;
  extensions?: ExtensionData;
  id: Identifier;
  intentRef?: IntentRef;
  interfaceVersion: InterfaceVersion;
  nonce: NonNegativeIntegerString;
  pactRef?: PactRef;
  pathRef?: PathRef;
  paycardRef?: PaycardStreamRef;
  paymentTerms: PaymentTerms;
  proofPolicy: ProofPolicy;
  proposalRef?: ProposalRef;
  provenance: Provenance;
  settlementIntentRef?: SettlementIntentRef;
  status: "DRAFT" | "PREPARED" | "AWAITING_AUTHORIZATION" | "COMMITTED" | "EXECUTING" | "SETTLED" | "FAILED" | "CANCELLED" | "EXPIRED";
  workspaceRef?: WorkspaceRef;
};
export type RailsFlowInspectRequest = {
  railsflowRef: RailsFlowRef;
};
export type RailsFlowPayRequest = {
  proofRef?: ProofRef;
  railsflowRef: RailsFlowRef;
  settlementIntentRef: SettlementIntentRef;
};
export type RailsFlowRef = ObjectRef & {
  type?: "RailsFlow";
};
export type RailsFlowRequest = {
  railsflow: RailsFlow;
};
export type RailsFlowResponse = {
  railsflow: RailsFlow;
};
export type Receipt = {
  amount?: NonNegativeIntegerString;
  asset?: Asset;
  canonicalReconciliation: CanonicalReconciliation;
  createdAt: Timestamp;
  executionProfile: ExecutionProfile;
  extensions?: ExtensionData;
  financialOutcome: "NONE" | "PENDING" | "RECONCILED" | "REJECTED";
  id: Identifier;
  intentRef?: IntentRef;
  interfaceVersion: InterfaceVersion;
  network: NetworkReference;
  operationId: Identifier;
  pactRef?: PactRef;
  pathRef?: PathRef;
  proposalRef?: ProposalRef;
  provenance: Provenance;
  receiptStatus: "VERIFIED" | "UNVERIFIED" | "REJECTED";
  receiptType: "AUTHORIZATION" | "CLAIM" | "CLEARING" | "SETTLEMENT" | "RESIDUAL" | "RECONCILIATION";
  transaction: TransactionState;
  verification: {
    exact?: ExactVerification;
    reasons: Array<string>;
    status: "VERIFIED" | "UNVERIFIED" | "REJECTED";
  };
  workspaceRef?: WorkspaceRef;
};
export type ReceiptListRequest = {
  network?: NetworkReference;
  subject?: Subject;
};
export type ReceiptListResponse = {
  receipts: Array<Receipt>;
};
export type ReceiptRef = ObjectRef & {
  type?: "Receipt";
};
export type ReceiptRefRequest = {
  objectRef: ReceiptRef;
};
export type ReceiptResponse = {
  receipt: Receipt;
};
export type ReceiptVerifyRequest = {
  receiptRef: ReceiptRef;
};
export type RectificationObligation = {
  assigneeRef: ActorRef;
  caseRef: GaiaCaseRef;
  dueAt: Timestamp;
  extensions?: ExtensionData;
  id: Identifier;
  interfaceVersion: InterfaceVersion;
  obligationType: "REFUND" | "RETRY" | "CORRECT_USAGE_RECORD" | "PROVIDE_EVIDENCE" | "MANUAL_REVIEW";
  provenance: Provenance;
  status: "OPEN" | "IN_PROGRESS" | "FULFILLED" | "DISPUTED" | "CANCELLED";
  terms: {
    amount?: NonNegativeIntegerString;
    asset?: Asset;
    description: string;
  };
};
export type RectificationObligationRef = ObjectRef & {
  type?: "RectificationObligation";
};
export type SchemaIndex = {
  canonicalFormat: "JSON Schema 2020-12";
  interfaceVersion: InterfaceVersion;
  schemas: Array<{
    $id: string;
    name: string;
    path: string;
  }>;
};
export type SettlementIntent = {
  executionProfile: ExecutionProfile;
  extensions?: ExtensionData;
  id: Identifier;
  intentRef: IntentRef;
  interfaceVersion: InterfaceVersion;
  network: NetworkReference;
  pactRef?: PactRef;
  pathRef?: PathRef;
  paymentTerms: PaymentTerms;
  proposalRef?: ProposalRef;
  provenance: Provenance;
  signatureBinding: SignatureBinding;
  status: "PREPARED" | "AWAITING_AUTHORIZATION" | "AUTHORIZED" | "EXPIRED" | "REVOKED";
  workspaceRef?: WorkspaceRef;
};
export type SettlementIntentRef = ObjectRef & {
  type?: "SettlementIntent";
};
export type SignatureBinding = {
  chainId: ChainId;
  domain: SignatureDomain;
  expiresAt: Timestamp;
  issuedAt: Timestamp;
  nonce: NonNegativeIntegerString;
  signature: HexData;
  signer: NonZeroAddress;
  verifyingContract: NonZeroAddress;
};
export type SignatureDomain = {
  chainId: ChainId;
  name: string;
  salt?: Hash;
  verifyingContract: NonZeroAddress;
  version: string;
};
export type Subject = {
  actorRef?: ActorRef;
  role?: "owner" | "payer" | "recipient" | "delegate" | "operator" | "observer";
  walletAddress?: NonZeroAddress;
} & ({
  actorRef: ActorRef;
} | {
  walletAddress: NonZeroAddress;
});
export type SubjectObjectRef = ObjectRef & {
  type?: "Actor" | "Intent" | "Proposal" | "RailsFlow" | "RailsCard" | "PaycardStream" | "Receipt" | "WorkUsageEvent" | "GaiaCase" | "RectificationObligation";
};
export type Timestamp = string;
export type TransactionState = {
  blockHash?: Hash;
  blockNumber?: NonNegativeIntegerString;
  confirmations?: NonNegativeIntegerString;
  confirmedAt?: Timestamp;
  failureCode?: ErrorCode;
  failureReason?: string;
  financialEffect: "NONE" | "PENDING" | "UNKNOWN" | "RECONCILIATION_REQUIRED";
  interfaceVersion: InterfaceVersion;
  network: NetworkReference;
  nonce?: NonNegativeIntegerString;
  observedAt: Timestamp;
  status: TransactionStateName;
  submittedAt?: Timestamp;
  txHash?: Hash;
};
export type TransactionStateName = "NOT_REQUESTED" | "WALLET_REQUIRED" | "WALLET_REJECTED" | "SUBMITTED" | "PENDING_CONFIRMATION" | "CONFIRMED" | "REVERTED" | "REPLACED" | "DROPPED" | "UNKNOWN";
export type TransactionStateRef = ObjectRef & {
  type?: "TransactionState";
};
export type TransitionRules = {
  allowedTransitions: Array<{
    allowedProfiles: Array<ExecutionProfile>;
    financialEffect: "NONE" | "PENDING" | "COMMITTED" | "RECONCILED" | "UNKNOWN";
    from: LifecycleState;
    requires?: Array<"WALLET_AUTHORIZATION" | "CONFIRMED_TRANSACTION" | "VERIFIED_PROOF" | "EXACT_RECEIPT" | "CANONICAL_VAULT_RECONCILIATION" | "ALLOW_DECISION" | "PACT">;
    to: LifecycleState;
    trigger: string;
  }>;
  interfaceVersion: InterfaceVersion;
  lifecycleStates: Array<LifecycleState>;
  outcomeRules: Array<{
    errorCode: null | ErrorCode;
    financialEffect: "NONE" | "PENDING" | "COMMITTED" | "RECONCILED" | "UNKNOWN";
    lifecycleState: LifecycleState;
    notes?: string;
    outcome: "success" | "blocked" | "failed" | "cancelled" | "signature-expired" | "transaction-reverted" | "wrong-network" | "rpc-unavailable";
    receiptRequirement: "none" | "exact-verified-receipt-and-reconciliation" | "unverified-receipt-only";
    retryable?: boolean;
    transactionState: TransactionStateName;
    valueMovementAllowed: boolean;
  }>;
  transactionStates: Array<TransactionStateName>;
};
export type ValidationResponse = {
  errors: Array<InterfaceError>;
  valid: boolean;
};
export type WorkUsageEvent = {
  actorRef: ActorRef;
  canonicalSettlementState: false;
  eventType: string;
  extensions?: ExtensionData;
  id: Identifier;
  interfaceVersion: InterfaceVersion;
  metadata?: {
    idempotencyKey?: Identifier;
    source?: string;
  };
  observedAt: Timestamp;
  provenance: Provenance;
  quantity: NonNegativeIntegerString;
  subjectRef: SubjectObjectRef;
  unit?: string;
};
export type WorkUsageEventRef = ObjectRef & {
  type?: "WorkUsageEvent";
};
export type Workspace = {
  createdAt: Timestamp;
  description?: string;
  extensions?: ExtensionData;
  id: Identifier;
  interfaceVersion: InterfaceVersion;
  name: string;
  ownerActorRef: ActorRef;
  provenance: Provenance;
  status: "DRAFT" | "ACTIVE" | "SUSPENDED" | "CLOSED";
  updatedAt: Timestamp;
};
export type WorkspaceListResponse = {
  workspaces: Array<Workspace>;
};
export type WorkspaceMember = {
  actorRef: ActorRef;
  extensions?: ExtensionData;
  id: Identifier;
  interfaceVersion: InterfaceVersion;
  joinedAt: Timestamp;
  permissions?: Array<Identifier>;
  provenance: Provenance;
  role: "owner" | "administrator" | "operator" | "member" | "observer";
  status: "INVITED" | "ACTIVE" | "SUSPENDED" | "REMOVED";
  workspaceRef: WorkspaceRef;
};
export type WorkspaceMemberRef = ObjectRef & {
  type?: "WorkspaceMember";
};
export type WorkspaceRef = ObjectRef & {
  type?: "Workspace";
};
export type WorkspaceRefRequest = {
  objectRef: WorkspaceRef;
};
export type WorkspaceRequest = {
  workspace: Workspace;
};
export type WorkspaceResponse = {
  workspace: Workspace;
};
