import { Link } from "react-router-dom";
import { Footer } from "../gasok/components/Footer";
import { ProductShell } from "../gasok/components/ProductShell";
import { RuntimeArchitecture } from "../gasok/components/RuntimeArchitecture";
import "../gasok/styles.css";

export default function Build() {
  return <ProductShell footer={<Footer />}><main className="editorial-page build-page"><section className="page-hero"><span className="tech-label">BUILD / VERSIONED INTERFACE</span><h1>Infrastructure for accountable<br /><span>programmable commerce.</span></h1><p>The OpenRails runtime coordinates policy, action state, verification, Arc observation, and bounded rectification without owning a signing key.</p></section><RuntimeArchitecture /><section className="build-evidence"><div><span>SDK</span><strong>Prepare bounded payment actions</strong><small>Typed inputs, projected economics, metadata binding, wallet adapters, and transaction-ready output.</small></div><div><span>MCP</span><strong>Read and prepare without signing</strong><small>Agent tools expose state and prepare actions while keeping signing authority outside the server.</small></div><div><span>REST</span><strong>One versioned integration boundary</strong><small>Workspace, proposal, Pact, Proof, payment, and receipt operations for webapps and service clients.</small></div></section><section className="interface-ledger"><div className="section-index"><span>02</span><strong>INTERFACE CONTRACTS</strong></div><div className="interface-grid"><article><span>PROPOSAL</span><code>{`{ workspaceId, pathId, action, value, counterparty }`}</code><p>A requested commercial action. It is neither authority nor a transaction.</p></article><article><span>DECISION</span><code>{`{ result: "ALLOW", pathHash, proposalHash, reasonCodes }`}</code><p>The policy result binds an outcome to the exact authority and economic state evaluated.</p></article><article><span>OBSERVATION</span><code>{`{ chainId: 5042002, txHash, blockNumber, status }`}</code><p>Arc observation advances financial state only after receipt verification.</p></article></div></section><section className="build-closing"><span>03 / AUTHORIZATION BOUNDARY</span><h2>The Runtime coordinates.<br />The wallet authorizes.<br />Arc finalizes.</h2><Link to="/docs">Read integration documentation →</Link></section></main></ProductShell>;
}
